spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java_gobang?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 980515Qq!!
    driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis相关配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true  # 开启驼峰命名
# 映射文件位置
  mapper-locations: classpath:mapper/**Mapper.xml